# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 05:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('idComida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('categorias', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Cerdo'), (1, 'Chino'), (2, 'Completos'), (3, 'Egipcio'), (4, 'Empanadas'), (5, 'Ensalada'), (6, 'Japones'), (7, 'Pan'), (8, 'Papas fritas'), (9, 'Pasta'), (10, 'Pescado'), (11, 'Pollo'), (12, 'Postres'), (13, 'Sushi'), (14, 'Vacuno'), (15, 'Vegano'), (16, 'Vegetariano')], max_length=40)),
                ('descripcion', models.CharField(max_length=500)),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('precio', models.PositiveSmallIntegerField(default=0)),
                ('imagen', models.ImageField(upload_to='productos')),
            ],
            options={
                'db_table': 'Comida',
            },
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Favoritos',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatars')),
            ],
            options={
                'db_table': 'imagen',
            },
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('idTransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreComida', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.IntegerField()),
                ('fecha', models.CharField(default='2017-06-26', max_length=200)),
            ],
            options={
                'db_table': 'transacciones',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.IntegerField(choices=[(0, 'admin'), (1, 'alumno'), (2, 'fijo'), (3, 'ambulante')])),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('activo', models.BooleanField(default=False)),
                ('formasDePago', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Efectivo'), (1, 'Tarjeta de Crédito'), (2, 'Tarjeta de Débito'), (3, 'Tarjeta Junaeb')], max_length=7, null=True)),
                ('horarioIni', models.CharField(blank=True, max_length=200, null=True)),
                ('horarioFin', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AddField(
            model_name='transacciones',
            name='idVendedor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='idAlumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_alumno', to='main.Usuario'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='idVendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_vendedor', to='main.Usuario'),
        ),
        migrations.AddField(
            model_name='comida',
            name='idVendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
